-- ==============================================================================
-- EquantEdge - Trade History Schema for Supabase / PostgreSQL
-- ==============================================================================
-- Run this script in your Supabase Dashboard: SQL Editor -> New Query -> Run

create table if not exists trades (
    id bigint generated by default as identity primary key,
    ticket bigint unique not null,
    symbol text not null,
    side text not null,                   -- 'BUY' or 'SELL'
    lot_size double precision not null,
    open_time timestamp with time zone not null,
    open_price double precision not null,
    sl double precision,
    tp double precision,
    session text,                         -- 'Asia', 'London', 'New York'
    ema_50 double precision,
    mother_high double precision,
    mother_low double precision,
    close_time timestamp with time zone,
    close_price double precision,
    profit_usd double precision,
    close_reason text,                    -- 'TP_HIT', 'SL_HIT', 'MANUAL', 'CLOSE'
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Fast lookup indexes
create index if not exists idx_trades_ticket on trades(ticket);
create index if not exists idx_trades_open_time on trades(open_time desc);
create index if not exists idx_trades_symbol on trades(symbol);
